[project]
name = "python-analytics-homework"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.1.0",
    "pandas>=2.3.3",
    "pandas-stubs~=2.3.3",
    "regex>=2025.11.3",
    "requests>=2.32.5",
    "seaborn>=0.13.2",
]
